EXPRESS:
    base_url: '/itsm-analytics/'
    socket_url: 'http://10.127.38.210:5111'

SOCKET:
    rememberTransport: false
    transports: ['WebSocket', 'Flash Socket', 'AJAX long-polling']

ERROR_MSG:
  403: 'Invalid parameters'
  500: 'Internal error, please contact Administrator of the system'
  404: 'End-point not found'
  method_not_allowed: 'Method not allowed on api'
  periodEnableQueryDate: 60
  periodEnableQueryDateMsg: 'The period between start and end date is too large, for query in real-time'

JWT:
    jwt_secret: 'secret'
    jwt_session:
        session: false
    msg:
        access_denied: 'Unauthorized access'

MONGO:
    user: 'admin'
    pwd: 'p4ssw0rd'
    uri: 'mongodb://%s:%s@localhost:27017/admin?autoMechanism=DEFAULT'
    port: 27017
    options:
        server:
            socketOptions:
                keepAlive: 1
                connectTimeoutMS: 30000
            poolSize: 30
        replset:
            socketOptions:
                keepAlive: 1
                connectTimeoutMS: 30000
    msg:
        bulkupdated: 
            result: 'Records were upserted with success result'

ITSM:
    period_delay: 90
    teams_to_erp: ["HMB SAP Accounting IT Team", "HMB SAP Production IT Team", "HMB SAP Sales IT Team", "HMB SAP Technical IT Team"]
    current_teams: ['Infra Service', 'ERP Service', 'CRM Service', 'MES Service']    
    hours_reduce: 11
    sch_eai:
        min: 5
    sch_metrics:
        min: 3
        sec: 20
    sch_sockets: 
        sec: 60
        min: 7
    sch_received:
        hour: 3
        sec: 20
    sch_resolved:
        hour: 3
        sec: 20
    EAI:
        PRD:
            endpointSync: 'http://10.121.241.115:5100/invoke/HMBITSM.inbound.ITSM_Analytics_Results.service/request'
            user: 'ramon'
            password: '995421'
        DEV:
            endpointSync: 'http://10.121.241.117:5200/invoke/HMBITSM.inbound.ITSM_Analytics_Results.service/request'
            user: 'ramon'
            password: '123456'